name: update-infra

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      provider:
        required: true
        type: string
      aws_account:
        required: true
        type: string

jobs:
  apply-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.7
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account }}:role/XXXXXXXXXX
          aws-region: us-east-1

      - name: Initialize project
        working-directory: ./infra/${{ inputs.provider }}/
        run: terraform init -backend-config=env/${{ inputs.env }}/backend.hcl  -var-file=env/${{ inputs.env }}/${{ inputs.env }}.tfvars -reconfigure

      - name: Terraform Plan
        working-directory: ./infra/${{ inputs.provider }}/
        run: terraform plan -var-file=env/${{ inputs.env }}/${{ inputs.env }}.tfvars -out=tfplan

      - name: Apply Infra
        working-directory: ./infra/${{ inputs.provider }}/
        id: apply_infra
        run: terraform apply -auto-approve tfplan
